name: Build public

on:
  push:
    branches:
      - master
    # paths:
    #   - public/*/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install, build, and test
      run: |
        cd public
        npm install
        npm run build
    - name: debug
      run: |
        ls -la
        ls -la public
    - name: upload archive
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: public/dist
